wallpaper {
    monitor = DP-1
    path = ~/external/wallz/Greenify/
    fit_mode = cover
    timeout = 600
}

wallpaper {
    monitor = DP-3
    path = ~/external/wallz/Green Lush/
    fit_mode = cover
    timeout = 600
}

splash = false
